language: node_js
node_js: stable

cache:
    apt: true
    directories:
        - node_modules

notifications:
    email:
        recipients:
            - steven_mhy@qq.com #你的邮箱地址
        on_success: always 
        on_failure: always

# turn off the clone of submodules for change the SSH to HTTPS in .gitmodules to avoid the error
git:
  submodules: false
        
before_install:
    - export TZ='Asia/Shanghai'
    - npm install hexo-cli -g 

install:
    - npm install
    - echo 'KEY' >> $HOME/.ssh/known_hosts

script:
    - hexo g

after_script:
  - git init
  - git config user.name "GaisaiYuno"
  - git config user.email "steven_mhy@outlook.com"
  - git fetch --unshallow ${GH_REF}
  - git add .
  - git commit -m "Update blog content by Travis CI to Github"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  

branches:
    only:
        - master

env:
    global:
        # Github Pages
        - GH_REF: github.com/GaisaiYuno/gaisaiyuno.github.io
        - GT_REF: gitee.com/steven_meng/steven_meng