############################### 基本信息 ###############################
info:
  name: Material X
  docs: https://xaoxuu.com/wiki/material-x/
  cdn:   # 把对应的那一行注释掉就使用本地的文件
    css: # 使用本地的css
      #style: https://gitee.com/steven_meng/cdn/raw/master/style.css
    js:
      app: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.8/js/app.js
      search: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.8/js/search.js
      volantis: https://cdn.jsdelivr.net/gh/xaoxuu/volantis@1.0.5/js/volantis.min.js

############################### 主题风格 ###############################
# style: material    # material: 导航栏和标题栏背景是主题色
style: pure        # pure: 导航栏和标题栏背景是白色
url: http://stevenmhy.tk


############################### 服务开关 ###############################
scrollreveal: false
nodewaves: true
# busuanzi: true
# 开启了no-referrer，就不能用不蒜子统计了
fastclick: true

widget_pack:
  enable: true
  hint: 来了就留下您的评分吧！
  id: 21085

############################### 默认值 ###############################
# 音乐控件的默认配置，如果sidebar或者page里没有提供，就取这里的参数
music:
  enable: true         # 是否启用
  own: false           # 是否使用自己的music.js
  path: /js/music.js   # 使用在线歌单，这里不填
  color: '#1BCDFC'     # 主题色
  mode: circulation    # random （随机） single （单曲） circulation （列表循环） order （列表）
  server: netease      # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
  type: playlist       # song （单曲） album （专辑） playlist （歌单） search （搜索）
  id: 2482575335       # 歌曲/专辑/歌单 ID
  volume: 0.7          # 音量, 0~1
  autoplay: false      # 自动播放

# 友链页头像占位图因为使用pjax，被我阉割掉了

# 日期格式 http://momentjs.com/docs/
date_format: 'YYYY-MM-DD' # 文章发布日期的格式
updated_date_format: 'll' # 文章更新日期的格式

# 幻灯片
backstretch:
  position: full  # cover: 封面背景   full: 整个网页背景
  duration: 6000 # 持续时间（毫秒）
  fade: 2500     # 渐变（毫秒）
  images:
    - https://img.xjh.me/desktop/bg/nature/65253358_p0.jpg

############################### 自定义 ###############################
# page的封面
cover:
  scheme: search    # 后期将会提供多种封面方案
  height: half      # full（默认值）: 首页封面占据整个第一屏幕，其他页面占半个屏幕高度， half: 所有页面都封面都只占半个屏幕高度
  title: "Steven_MengのBlog"
  # logo: assets/logo.png    # logo和title只显示一个，若同时设置，则只显示logo
  # search_placeholder: '搜索'
  # 主页封面菜单
  
  features:
    - name: 主页
      icon: fas fa-home
      url: /
    - name: 友链
      icon: fas fa-link
      url: friends/
      rel: nofollow
    - name: 关于
      icon: fas fa-info-circle
      url: about/
      rel: nofollow
    - name: 2048游戏
      icon: fas fa-th
      url: 2048-master/
      rel: nofollow
    - name: BZOJ离线题库
      icon: fas fa-book
      url: bzojch/
      rel: nofollow
    - name: Markdown在线编辑
      icon: fas fa-edit
      url: editor/
      rel: nofollow
    - name: 留言板
      icon: fas fa-comment
      url: /message
    - name: 实验室
      icon: fas fa-fire
      url: lab/
      rel: nofollow


# 桌面端导航栏菜单
menu_desktop:

# 手机端导航菜单（从右上角的按钮点击展开）
menu_mobile:
  - name: 近期文章
    icon: fas fa-clock
    url: /
  - name: 文章归档
    icon: fas fa-archive
    url: blog/archives/
    rel: nofollow
  - name: 开源项目
    icon: fas fa-code-branch
    url: projects/
  - name: 我的友链
    icon: fas fa-link
    url: friends/
    rel: nofollow
  - name: 主题文档
    icon: fas fa-book
    url: https://xaoxuu.com/wiki/material-x/
    rel: nofollow
  - name: 关于小站
    icon: fas fa-info-circle
    url: about/
    rel: nofollow

# 默认的meta信息，文章中没有配置则按照这里的配置来显示，设置为false则不显示
# 其中，title只在header中有效，music和thumbnail无需在这里设置，文章中有则显示
# 如果tags放置在meta.header中，那么在post列表中不显示（因为卡片下方已经有了）

meta:
  header: [title, author, date, categories, counter, top, thumbnail]
  footer: [updated, tags, share]

# 主体元素，你也可以在页面的Front-matter中设置
body: [article, comments]

latest_comments:
  enable: true
  repo: gaisaiyuno/gaisaiyuno.github.io # 您的repo地址（最新评论用）

# 侧边栏小部件，默认按下面给定的顺序全部显示，文章中还可以自定义显示一部分以及顺序
sidebar:
  - widget: author
    avatar: https://cdn.jsdelivr.net/gh/GaisaiYuno/imghost/20200124153036.PNG
    social: true
  
  - widget: toc

  - widget: plain
    icon: fas fa-bullhorn
    title: 公告
    body: '[博客源代码](https://github.com/GaisaiYuno/blog)已经公开，如果访问缓慢，可以到[镜像网站](https://steven_meng.gitee.io/)。'

  - widget: grid
    icon: fas fa-map-signs
    title: 站内导航
    rows:
      - name: 文章归档
        icon: fas fa-archive
        url: /archives/
        rel: nofollow
      - name: 我的友链
        icon: fas fa-link
        url: friends/
        rel: nofollow
      - name: 关于小站
        icon: fas fa-info-circle
        url: about/
        rel: nofollow

  - widget: category
    more:
      icon: fas fa-expand-arrows-alt
      url: blog/categories/
      rel: nofollow

  - widget: tagcloud
	
  - widget: latest_comments

  # - widget: related_posts # 需要安装插件  npm i -S hexo-related-popular-posts
  
  - widget: hitokoto


# 社交信息
social:
  - icon: fas fa-envelope
    url: mailto:steven_mhy@qq.com
  - icon: fab fa-github
    url: https://github.com/GaisaiYuno
  - icon: fas fa-code
    url: https://www.luogu.com.cn/user/45109
  - icon: fas fa-headphones-alt
    url: https://music.163.com/#/user/home?id=1650189892
  - icon: fab fa-zhihu
    url: https://www.zhihu.com/people/stevenmhy


# 分享按钮
# 当id为qrcode时需要安装插件  npm i -S hexo-helper-qrcode
share:
  - id: qq
    name: QQ好友
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qq.png
  - id: qzone
    name: QQ空间
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qzone.png
# - id: qrcode
#   name: 微信
#   img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/wechat.png
  - id: weibo
    name: 微博
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/weibo.png
# - id: qrcode
#   name: QRcode
#   img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qrcode.png



footer: 'Copyright StevenMeng@2019' # 填上您的大名


############################### 评论系统 ###############################
# disqus_shortname: 要使用哪个请复制到根目录配置文件！
# livere_uid: 要使用哪个请复制到根目录配置文件！
# leancloud: 要使用哪个请复制到根目录配置文件！
#   app_id: 你的appId
#   app_key: 你的appKey

############################### 杂项，请勿删除 ###############################
#valine配置（暂不支持）
valine:
  enable: false # 如果你想用Valine评论系统，请设置enable为true
  volantis: false # 是否启用volantis版本（禁止匿名，增加若干贴吧、QQ表情）
  # 还需要在根目录配置文件中添加下面这三行内容
  # leancloud:
  #   app_id: 你的appId
  #   app_key: 你的appKey
  guest_info: nick,mail,link #valine comment header info
  placeholder: 快来评论吧~ # valine comment input placeholder(like: Please leave your footprints )
  avatar: mp # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: true # valine verify code (true/false)
  notify: true # valine mail notify (true/false)
  lang: zh-cn
  highlight: true

# 搜索配置
search:
  enable: true
  service: hexo
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Less渲染
less:
  compress: true
